import Head from "next/head";
import SignIn from "@auth//screens/SignIn";
import { LayoutPage } from "next";
import Auth from "@layouts/Auth";

const Home: LayoutPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SignIn />
    </>
  );
};

Home.getLayout = (page) => <Auth>{page}</Auth>;

export default Home;
